### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by backfromhiatus** [nano-proxy/nano#6]
file:///E:/0-safeguard/pico/node_modules/.pnpm/@rubynetwork+rh@1.2.74_bufferutil@4.0.8/node_modules/@rubynetwork/rh/src/classes/RammerheadJSFileCache.js:28
            throw new TypeError('disk cache folder does not exist: ' + diskJsCachePath);
                  ^

TypeError: disk cache folder does not exist: E:\0-safeguard\pico\node_modules\.pnpm\@rubynetwork+rh@1.2.74_bufferutil@4.0.8\node_modules\@rubynetwork\rh\cache-js
    at new RammerheadJSFileCache (file:///E:/0-safeguard/pico/node_modules/.pnpm/@rubynetwork+rh@1.2.74_bufferutil@4.0.8/node_modules/@rubynetwork/rh/src/classes/RammerheadJSFileCache.js:28:19)
    at file:///E:/0-safeguard/pico/node_modules/.pnpm/@rubynetwork+rh@1.2.74_bufferutil@4.0.8/node_modules/@rubynetwork/rh/src/config.js:70:14
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.
 
 Seems like dependancies arent installing correctly
any way to fix?

**Comment by Nebelung-Dev** [comment]
updated chemical to fix this
